# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 22:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=256)),
                ('tour_logo', models.URLField(verbose_name=b'URL of tour logo')),
                ('tour_id', models.SlugField(max_length=64, unique=True)),
                ('tour_organization', models.CharField(max_length=256)),
                ('dcs_url', models.URLField(verbose_name=b'URL of DCS')),
                ('gcm_sender_id', models.CharField(max_length=64)),
                ('start_time', models.PositiveIntegerField()),
                ('max_tour_time', models.PositiveIntegerField()),
                ('is_cancelled', models.BooleanField(default=False, verbose_name=b'Cancel the tour?')),
                ('server_polling_rate', models.PositiveIntegerField(default=600, verbose_name=b'Server Polling Rate (sec)')),
                ('location_polling_rate', models.PositiveIntegerField(default=45, verbose_name=b'Device Location Polling Rate (sec)')),
                ('server_polling_range', models.PositiveIntegerField(default=5, verbose_name=b'Server Polling Range (sec)')),
            ],
            options={
                'verbose_name': 'tour',
            },
        ),
        migrations.CreateModel(
            name='TourRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('route', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='tourconfig',
            name='tour_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour_config.TourRoute'),
        ),
    ]
