# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affinity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity_Group_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affinity.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('os', models.CharField(blank=True, max_length=125, null=True)),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('push_id', models.CharField(blank=True, max_length=512, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('affinity_group', models.ManyToManyField(through='rider.Affinity_Group_Mapping', to='affinity.Group')),
            ],
        ),
        migrations.AddField(
            model_name='affinity_group_mapping',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.Rider'),
        ),
        migrations.AlterUniqueTogether(
            name='affinity_group_mapping',
            unique_together=set([('rider', 'affinity_group')]),
        ),
    ]
