# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 22:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour_config', '0001_initial'),
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.FloatField(blank=True, default=None, null=True)),
                ('time', models.BigIntegerField()),
                ('accuracy', models.FloatField(blank=True, default=None, null=True)),
                ('battery', models.FloatField(blank=True, default=None, null=True)),
                ('provider', models.CharField(blank=True, default=None, max_length=50)),
                ('bearing', models.FloatField(blank=True, default=None, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.Rider')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_config.TourConfig', to_field=b'tour_id')),
            ],
        ),
    ]
